### ISSUE TITLE
wrong ressource/lang loaded... 

### ISSUE THREAD

**Issue by FrancoisDucobu** [InvolvedGroup/laravel-lang-country#13]
Hello,

I live in Belgium and I develop an application in french, dutch and I think about trying to sell this application in France.
Some words are different in French Belgian and French France...
In Belgium, the administration is called "Administration Communale" in French Belgian
And called "Mairie" in French France

I found your package.
It is very usefull !

But I have an issue and I think there's something I didn't understand correctly.

So in my ressource/lang, I have 3 folders (nl-BE, fr-BE and fr-FR)
In my session variable, i got 'lang' => 'fr', and 'lang_country' => 'fr-BE'
But the application load the 'fr' language...

In the README file, you wrote :
```
There will ALWAYS be set three sessions:
lang_country (example: nl-BE)
locale (examples: nl, es-CO)
locale_for_date (example: nl)
```
So I thought that locale would contain "fr-BE" instead of "fr"

here is my config/lang-country.php

```
return [

    'fallback' => 'fr-BE',

    'allowed' => [
        'nl-BE',
        'fr-BE',
        'fr-FR',
    ],

    'lang_switcher_middleware' => ['web'],

];
```

Did I miss something ?

Thanks for your help.

Francois

**Comment by stefro** [comment]
Hi Francois, great to hear you're enjoying this package!
I see in the embedded data, that we've been using the 'fr' locale for both Belgium and France. We're using it like that because we're only using the date functionality for this language.
For you, it makes sense to be able to override our defaults using the config file. However, this is not implemented (yet). I need to finds some time to make this. Of course, I will also accept a PR for this!

I'm thinking about an overwrite array like this in the config file where you can completely override the default:
```php
    "override" => [
        "fr-FR" => [
            "country": "FR",
            "lang": "fr-FR",
            "name": "Français",
            "date_numbers": "d/m/Y",
            "date_numbers_full_capitals": "DD/MM/YYYY",
            "date_words_without_day": "j F Y",
            "date_words_with_day": "l j F Y",
            "date_birthday": "j F",
            "time_format": "H:i",
            "emoji_flag": "🇫🇷"
        ]
    ]


```

**Comment by FrancoisDucobu** [comment]
Hi Stefro,

Thanks for your reply.
I now understand why this is "not working"
I will sell my application in France on second quarter of next year so it's not urgent.

Thanks for your work !
It help me a lot !

Regards,

Francois

**Comment by stefro** [comment]
Version 1.0.12 makes it possible to override the default json files. https://github.com/InvolvedGroup/laravel-lang-country#override-lang-country-properties

**Comment by FrancoisDucobu** [comment]
Thanks Stefro.
I will try that tomorrow !

Thanks for your work.

**Comment by stefro** [comment]
You're welcome. Good luck!
