### ISSUE TITLE
en-GB date format incorrect

### ISSUE THREAD

**Issue by davidphtee** [InvolvedGroup/laravel-lang-country#23]
Loving this but, as a Brit we always use day-month-year for our dates. It should really be like en-AU. More at https://en.wikipedia.org/wiki/Date_format_by_country

{
  "country": "GB",
  "lang": "en",
  "name": "English",
  "date_numbers": "d/m/Y",
  "date_numbers_full_capitals": "DD/MM/YYYY",
  "date_words_without_day": "j F Y",
  "date_words_with_day": "l j F Y",
  "date_birthday": "j F",
  "time_format": "h:i a",
  "emoji_flag": "🇬🇧"
}

**Comment by stefro** [comment]
Thanks @davidphtee 
I've changed it and merged into master. Will tag a new version soon.
