### ISSUE TITLE
date example in readme is incirrect.

### ISSUE THREAD

**Issue by jayenne** [InvolvedGroup/laravel-lang-country#27]
Hi,
the example date in the readme file is incrrect. I don't know if this is a typo of something that reflects the code too...

you have: jan 1th 2018; 1 jan 2018

it should be: jan 1st 2018; 1st jan 2018
--also: you would only really drop the st/nd/rd/th if the month is a number too.

**Comment by stefro** [comment]
Hi.
Yes, this is a typo. This package does not do any translating itself, it uses the Carbon translations. Thanks for noticing, I will change this in the documentation.
