### ISSUE TITLE
lang_country not stored in DB as expected

### ISSUE THREAD

**Issue by jayenne** [InvolvedGroup/laravel-lang-country#28]
Hello,
I have followed the instructions to install this package and expected the lang_country to be stored in the new user.lang_country table of my database but it remains NULL even after numerous logins and cache dumps etc.

Should it be added to the db or do I need to add it manually on login somehow?

**Comment by stefro** [comment]
Did you implement this in your LoginController?
```php
public function authenticated(Request $request, $user)
{
    // Set the right sessions
    if (null != $user->lang_country) {
        \LangCountry::setAllSessions($user->lang_country);
    }

    return redirect()->intended($this->redirectPath());
}
```

**Comment by jayenne** [comment]
Kind of yes (it's in a listener but essentially the same).
I may missunderstand the full functionality process but as far as I can tell, it only updates the users table 'lang_country' when you switch languages. It doesn't set the 'lang_country' field on logging in unless you switch languages correct?

My scenario. a guest registers via socialite. This creates a new user but doesn't set a value for 'lang_country' (leaving it NULL).

*on 'authenticated' checks for !null then sets session.

for demo purposes I set the fallback to `es_ES` and register through twitter via socialite. (my browser is using `en_GB`).

My login creates a new user and `lang_country` defaults to NULL.

what I can see: The session is set and the `lang_country` is set to `en_GB` (and not the fallback) as hoped for. However, the `users.lang_country` is not set to `en_GB` as expected.

Is it supposed to set the `lang_country` only once a user has "switched" language?

Is it suposed to set the `lang_country` if it is NULL on login ?

I'd like (if it doesnot already) the package to set the `lang_country` to the same as the session if the `users.lang_country` is NULL else only update on amual "switch" ...does this sound like a good idea to you?

thanks.

**Comment by stefro** [comment]
Hi @jayenne 

A lot of questions in this one 😊

> Kind of yes (it's in a listener but essentially the same).

Are you sure? The middleware is first in the request lifecycle, and it will set the correct session for you. You need this session.

> My scenario. a guest registers via socialite. This creates a new user but doesn't set a value for 'lang_country' (leaving it NULL).

Two options here:
* Option 1: Make use of the `LangCountry::allLanguages();` helper. You can use this to make a dropdown in your signup form so the user can select the prefered language.
* Option 2 (what I do most of the time): Make the signup form translatable and make sure the middleware is also applied here. Then you don't need a dropdown for the available languages. You can set the lang_country on the user creation in your controller based on the `session('lang_country')`

Hope this helps!

**Comment by jayenne** [comment]
Thanks for the info Stefro.
DEfinately sure the code works and the session is being set. the route works too and it set the db as expect. I think I was expecting the package to set the db to the derived country/language if it found it to be null. By your asnwer, I think that it doesn't ans so there is no problem :)
...other than my own missunderstanding.
Thank you.

**Comment by stefro** [comment]
No problem! Hope you can use the package as needed. Let me know if you have any more questions. Good luck!
