### ISSUE TITLE
Override language file not found

### ISSUE THREAD

**Issue by rabol** [InvolvedGroup/laravel-lang-country#44]
I have created a da-DK.json, and put it in the lang/lang-country-overrides folder, however I get this error:

```
file_get_contents(/Users/rabol/code/web/test/vendor/stefro/laravel-lang-country/src/LangCountryData/da-DK.json): Failed to open stream: No such file or directory
```

**Comment by rabol** [comment]
missing '/'

```php
private function getDataFromFile(?string $lang_country): array
    {
        if ($lang_country === null) {
            throw new Exception('The lang_country session is not set');
        }

        if (file_exists(lang_path('lang-country-overrides') . '/' . $lang_country . '.json')) {
            $resource = lang_path('lang-country-overrides') . '/' .$lang_country . '.json';
        } else {
            $resource = __DIR__ . '/LangCountryData/' . $lang_country . '.json';
        }

        return json_decode(file_get_contents($resource), true);
    }
    ```

**Comment by stefro** [comment]
@rabol Thank you for your observations of the issues. I'll make sure I'll schedule some time asap to look into it.

**Comment by stefro** [comment]
@rabol I've just made a fresh install of Laravel Jetstream ans pulled in the Laravel LangCountry package. I've added an override language as shown below and was also successful by switching to the `da-DK` language.

![CleanShot 2023-10-19 at 18 37 17](https://github.com/stefro/laravel-lang-country/assets/5249559/776907a2-b9e3-4673-a402-0018398636f7)

![CleanShot 2023-10-19 at 18 36 45](https://github.com/stefro/laravel-lang-country/assets/5249559/68e415e0-fd16-4bb4-bb51-f231f02fd61d)

By the looks of your error message, It seems like it was not able to find the override file in the `lang/lang-country-overrides` dir, so it will try to load the file from the package `LangCountryData `. Can you check your `lang/lang-country-overrides` path? Also, maybe you're using a custom `lang_path()`?

**Comment by stefro** [comment]
Fixed in https://github.com/stefro/laravel-lang-country/pull/46
