### ISSUE TITLE
Your repository packagist may not working.

### ISSUE THREAD

**Issue by askaralimkndr** [InvolvedGroup/laravel-lang-country#56]
![e1](https://github.com/stefro/laravel-lang-country/assets/57449662/1c5a9ab7-ca96-43c6-812d-4b524bc1b35d)

**Comment by stefro** [comment]
@askaralimkndr It looks like a timeout in your screenshot. Maybe there was a short fail on packagist or on your internet connection.
I was just able to install the package without any problems. Can you try again?

**Comment by askaralimkndr** [comment]
@stefro Thanks it's working now, that's may be an issue with packagist.

**Comment by stefro** [comment]
@askaralimkndr Great to hear it's working now, enjoy!
